#!/bin/bash

# Script to sync game rankings and adhoc points JSON files to git repository
# Usage: Run this script via cron to automatically commit and push changes

# Set working directory
cd /home/ec2-user/projects/webdev/random/random

# Set git configuration if not already set (for cron environment)
git config --global user.email "noreply@conundrumclub.com" 2>/dev/null || true
git config --global user.name "Conundrum Club Auto-Sync" 2>/dev/null || true

# Files to track
RANKINGS_FILE="data/game-rankings.json"
ADHOC_FILE="data/adhoc-points.json"
FILES_CHANGED=""

# Check if the rankings file exists
if [ ! -f "$RANKINGS_FILE" ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: $RANKINGS_FILE not found"
    exit 1
fi

# Check if the adhoc points file exists (create if it doesn't)
if [ ! -f "$ADHOC_FILE" ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - WARNING: $ADHOC_FILE not found, creating empty file"
    echo '{"points": []}' > "$ADHOC_FILE"
fi

# Add both files to staging to check for changes
git add "$RANKINGS_FILE" "$ADHOC_FILE"

# Check if there are any changes to commit
if git diff --cached --quiet; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - No changes detected in tracked files"
    exit 0
fi

# Get current timestamp for commit message
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Count total games in the rankings file for commit message context
GAME_COUNT=$(grep -o '"2025-[0-9][0-9]-[0-9][0-9]"' "$RANKINGS_FILE" | wc -l)

# Count adhoc entries
ADHOC_COUNT=$(grep -o '"date"' "$ADHOC_FILE" | wc -l)

# Determine which files changed
FILES_UPDATED=""
if ! git diff --cached --quiet "$RANKINGS_FILE"; then
    FILES_UPDATED="$RANKINGS_FILE"
fi
if ! git diff --cached --quiet "$ADHOC_FILE"; then
    if [ -n "$FILES_UPDATED" ]; then
        FILES_UPDATED="$FILES_UPDATED and $ADHOC_FILE"
    else
        FILES_UPDATED="$ADHOC_FILE"
    fi
fi

# Create commit message
COMMIT_MSG="Update game data - $TIMESTAMP

- Updated: $FILES_UPDATED
- Total games tracked: $GAME_COUNT
- Total adhoc entries: $ADHOC_COUNT
- Auto-committed by sync script

🤖 Generated by Conundrum Club Auto-Sync"

# Commit the changes
echo "$(date '+%Y-%m-%d %H:%M:%S') - Committing changes to: $FILES_UPDATED"
git commit -m "$COMMIT_MSG"

# Check if commit was successful
if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: Failed to commit changes"
    exit 1
fi

# Push to origin master
echo "$(date '+%Y-%m-%d %H:%M:%S') - Pushing changes to origin master"
git push origin master

# Check if push was successful
if [ $? -eq 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Successfully synced rankings data to repository"
else
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: Failed to push to origin master"
    exit 1
fi
