#!/bin/bash

# Script to sync game rankings JSON file to git repository
# Usage: Run this script via cron to automatically commit and push changes

# Set working directory
cd /home/ec2-user/projects/webdev/random/random

# Set git configuration if not already set (for cron environment)
git config --global user.email "noreply@conundrumclub.com" 2>/dev/null || true
git config --global user.name "Conundrum Club Auto-Sync" 2>/dev/null || true

# File to track
JSON_FILE="data/game-rankings.json"

# Check if the JSON file exists
if [ ! -f "$JSON_FILE" ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: $JSON_FILE not found"
    exit 1
fi

# Add the file to staging to check for changes
git add "$JSON_FILE"

# Check if there are any changes to commit
if git diff --cached --quiet; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - No changes detected in $JSON_FILE"
    exit 0
fi

# Get current timestamp for commit message
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Count total games in the JSON file for commit message context
GAME_COUNT=$(grep -o '"2025-[0-9][0-9]-[0-9][0-9]"' "$JSON_FILE" | wc -l)

# Create commit message
COMMIT_MSG="Update game rankings data - $TIMESTAMP

- Updated $JSON_FILE
- Total games tracked: $GAME_COUNT
- Auto-committed by sync script

🤖 Generated by Conundrum Club Auto-Sync"

# Commit the changes
echo "$(date '+%Y-%m-%d %H:%M:%S') - Committing changes to $JSON_FILE"
git commit -m "$COMMIT_MSG"

# Check if commit was successful
if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: Failed to commit changes"
    exit 1
fi

# Push to origin master
echo "$(date '+%Y-%m-%d %H:%M:%S') - Pushing changes to origin master"
git push origin master

# Check if push was successful
if [ $? -eq 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Successfully synced rankings data to repository"
else
    echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR: Failed to push to origin master"
    exit 1
fi
